import AngularIcon from "./Angular.Icon";
import BootstrapIcon from "./Bootstrap.Icon";
import CopyIcon from "./Copy.Icon";
import CvIcon from "./Cv.Icon";
import DownloadArrowIcon from "./DownloadArrow.Icon";
import EmailIcon from "./Email.Icon";
import GitHubIcon from "./GitHub.Icon";
import JiraIcon from "./Jira.Icon";
import LinkedInIcon from "./LinkedIn.Icon";
import MoonIcon from "./Moon.Icon";
import NetIcon from "./Net.Icon";
import PhoneIcon from "./Phone.Icon";
import ReactIcon from "./React.Icon";
import RubyOnRailsIcon from "./RubyOnRails.Icon";
import SunIcon from "./Sun.Icon";
import TailwindIcon from "./Tailwind.Icon";
import TypescriptIcon from "./Typescript.Icon";
import UnityIcon from "./Unity.Icon";
import UnrealEngineIcon from "./UnrealEngine.Icon";

export const Angular = AngularIcon;
export const Bootstrap = BootstrapIcon;
export const Copy = CopyIcon;
export const Cv = CvIcon;
export const DownloadArrow = DownloadArrowIcon;
export const Email = EmailIcon;
export const GitHub = GitHubIcon;
export const Jira = JiraIcon;
export const LinkedIn = LinkedInIcon;
export const Moon = MoonIcon;
export const Net = NetIcon;
export const Phone = PhoneIcon;
export const React = ReactIcon;
export const RubyOnRails = RubyOnRailsIcon;
export const Sun = SunIcon;
export const Tailwind = TailwindIcon;
export const TypeScript = TypescriptIcon;
export const Unity = UnityIcon;
export const UnrealEngine = UnrealEngineIcon;